### ISSUE TITLE
Incorrect instructions (?) on how to build 

### ISSUE THREAD

**Issue by pbattino** [adperezmorales/confluence-manifold-connector#4]
According to ManifoldCF documentation:

> NOTE: Due to current limitations in the ManifoldCF Maven poms, you MUST run a complete "mvn clean install" as the first step. You cannot skip steps, or the build will fail.

I don't know if this is the reason, but in fact running
 `mvn clean install -DskipTests -Dmaven.test.skip` 
did not work for me while running 
`mvn clean install` 
did work (of course it took ages...)

**Comment by adperezmorales** [comment]
For me both instructions (installing skipping the tests and installing with tests) are working.
Anyway, I will modify the README.md to be aligned with ManifoldCF documentation (yes, it takes ages because it has to download many dependencies and also test dependencies)

**Comment by pbattino** [comment]
Forgive me if I'm missing a fundamental step (it's the first time I use mvn), but following the instructions verbatim I got other errors:
when I do 

`cd confluence-manifold-connector`
`mvn clean install -DskipTests -Dmaven.test.skip`
I get this error:
`
[WARNING] 'parent.relativePath' of POM org.apache.manifoldcf:mcf-confluence-repository-connector:[unknown-version] (/..etc..etc..etc../confluence-manifold-connector/confluence-repository-connector/pom.xml) points at org.apache.manifoldcf:mcf-confluence-connector instead of org.apache.manifoldcf:mcf-connectors, please verify your project structure @ line 3, column 10`
and after that a [FATAL] regarding the same issue. This is then repeated for the authority connector.
Looking at the structure of the other manifold connectors, I thought that confluence-repository-connector/ and confluence-authority-connector/ should perhaps be inside the /manifoldcf/connectors dir. So I MOVED those dir into /manifoldcf/connectors/ and run `mvn clean install` on both and it seems to have worked. Now I have *.jar files inside  /manifoldcf/connectors/confluence-respository-connector/ and the other one. (I don't know if this is correct, basically I never ran mvn clean install on the "main" confluence-manifold-connector )

But now I don't fine the _connector-lib_ folder !  There is no folder with this name...

**Comment by adperezmorales** [comment]
This connector is not integrated inside Manifold building yet, so you have to build Manifold and Confluence connector separately.

To build Manifold (using Maven or Ant) you can follow the guidelines provided in the official ManifoldCF documentation. Once you build Manifold you will have a connector-lib folder (on the ManifoldCF folder where you forked the project).

After that you can build the Confluence connector executing the provided Maven command on the confluence-manifold-connector folder which will build both Confluence Repository and Authority connectors. Then, inside the target folder of repository and authority connector modules, you can find the jars you should place in connector-lib folder before configuring the connectors in the connectors.xml file (inside example folder in ManifoldCF). Later, you can start ManifoldCF.

**Comment by pbattino** [comment]
OK sorry, I think I missed some steps, and it's related to Manifold build. I need to find out what's wrong with it, clearly the maven build did not run properly as I don't have a complete Manifold install. I'll try again. Thanks for your support!

**Comment by adperezmorales** [comment]
Don't worry, if you have problems building ManifoldCF let me know.
Only one thing, right now this connector has been developed using ManifoldCF 2.0.2 (as you can see in the project POM). It should work with newer versions of Manifold 2.X but try to download and build ManifoldCF version 2.0.2.
Anyway, I will modify the pom files to put ManifoldCF version in a Maven property to ease the ManifoldCF version change.

**Comment by pbattino** [comment]
> This connector is not integrated inside Manifold building yet, so you have to build Manifold and Confluence connector separately.

in this case can I just download Manifold 2.0.2 binaries instead of compiling it? (since the troubles were mainly due to compiling Manifold).
I'm doing a quick check, just copying the compiled (as above) Confluence connectors into a downloaded binary manifold 2.1 and it seems to work, at least I was able to add repository and authority.

**Comment by adperezmorales** [comment]
Yes, if you are able to compile the connector, you can use a binary distribution of ManifoldCF to test it, instead of building it from the source code

**Comment by pbattino** [comment]
I think it works! I can't tell for sure because I have a problem with my Confluence JSON-RPC API, I think it's not ON at the moment.

Have you tried using the REST API for authority connector as well? 
I tried 
`/rest/api/content/{id}/restriction/byOperation` 
and it seems to give me the correct info! They must have implemented it recently because I'm sure I tried some months ago and I was not able to get anything.

Anyhow, thank you very much for your work!

**Comment by adperezmorales** [comment]
Perfect. 
For the authority connector is not possible because it works at user level (once we have stored the permissions for a content). So the only way to get permissions at space level is using the JSON RPC API until they port it to the new REST API. Due to that, the implementation at this moment checks if the user accessing has the view permission in some spaces and returns those spaces as permissions. In the repository connector I store the space which the page belongs to as ACL and that's all right now.
